"""Generate committed L1 artifacts for test fixture apps.

Runs the full L1 pipeline (``build_index``) once per fixture app and persists
*only* its ``normalized/`` JSONL tree under ``tests/fixtures/artifacts/<app>/``.
Tests then load these via ``flawed.open_repo(path, artifact_root=...)`` with
**zero external tools** (no semgrep, no basedpyright) — the artifacts already
carry every L1 fact L2/L3 consume.

The ``raw/`` tree (semgrep core output) is intentionally NOT committed: the
loader (``load_index_from_artifacts``) reads only ``normalized/``.

A ``PIPELINE_VERSION`` stamp is written beside the artifacts so a stale set
(produced by an older extractor) is detectable; regenerate when the stamp no
longer matches the engine's ``_PIPELINE_VERSION``.

Usage::

    python -m tools.build_fixture_artifacts flask_basic functions   # named apps
    python -m tools.build_fixture_artifacts --all                   # every app
    python -m tools.build_fixture_artifacts --check flask_basic     # verify fresh
"""

from __future__ import annotations

import argparse
import multiprocessing
import os
import shutil
import sys
import time
from pathlib import Path

from flawed._index._pipeline import (
    _PIPELINE_VERSION,
    build_index,
)

_REPO_ROOT = Path(__file__).resolve().parent.parent
_APPS_DIR = _REPO_ROOT / "tests" / "fixtures" / "apps"
_ARTIFACTS_DIR = _REPO_ROOT / "tests" / "fixtures" / "artifacts"
_STAMP_NAME = "PIPELINE_VERSION"


# Directories whose direct ``.py`` files are each an INDEPENDENT single-file
# fixture app (one repo per file), rather than one multi-file app. ``detection/``
# holds ~30 standalone end-to-end detection fixtures, each opened individually by
# a session fixture as ``detection/<name>.py``. Listed explicitly because no
# structural signal cleanly distinguishes "flat bag of single-file fixtures" from
# "one package app whose modules happen to be flat" — and guessing wrong would
# either fuse unrelated fixtures into one index or split a real app apart.
_SINGLE_FILE_CONTAINER_DIRS = frozenset({"detection"})

# Namespace containers the test conftest ALSO loads as a single whole-repo fixture
# (root = the container itself), e.g. ``load_fixture("semantic/flask_nested_blueprint")``.
# `_all_apps` otherwise skips a container that holds no direct ``.py`` and builds only
# its sub-apps, so the container's own artifacts would never be regenerated by ``--all``
# and would silently drift stale against the pipeline (the FLAW-309 builder-vs-conftest
# discovery gap). Listed explicitly because nothing in the tree distinguishes a
# load-as-whole container from a pure namespace package.
_WHOLE_CONTAINER_APPS = frozenset(
    {"semantic/flask_nested_blueprint", "semantic/flask_sibling_apps"}
)


def _app_path(name: str) -> Path:
    """Resolve a fixture app *name* to its source path (file or directory)."""
    path = _APPS_DIR / name
    if not path.exists():
        msg = f"fixture app not found: {path}"
        raise SystemExit(msg)
    return path


def _has_direct_py(directory: Path) -> bool:
    """True if *directory* holds Python sources of its own.

    ``__init__.py`` alone does not count: a namespace container (e.g.
    ``semantic/``) that only packages sub-app directories is not itself an app.
    """
    return any(
        child.suffix == ".py" and child.name != "__init__.py"
        for child in directory.iterdir()
        if child.is_file()
    )


def _all_apps() -> list[str]:
    """Every fixture app under ``apps/``, as ``/``-relative names.

    Two kinds of app:
    - **Directory apps** — the top-most directory containing Python sources
      directly. Namespace containers (e.g. ``semantic/``) hold no ``.py`` of
      their own and are skipped; their children (``semantic/flask_basic``) are
      apps. A package app's sub-packages are excluded — only the root counts.
    - **Single-file apps** — for a ``_SINGLE_FILE_CONTAINER_DIRS`` directory
      (``detection/``), each direct non-``__init__`` ``.py`` is its own app
      (``detection/foo.py``); the container itself is not an app, but its
      sub-directories still count as ordinary directory apps (``detection/g091…``).
    """
    names: list[str] = []
    roots: list[Path] = []
    for directory in sorted(p for p in _APPS_DIR.rglob("*") if p.is_dir()):
        rel = directory.relative_to(_APPS_DIR)
        if directory == _APPS_DIR / rel.parts[0] and rel.parts[0] in _SINGLE_FILE_CONTAINER_DIRS:
            names.extend(
                str(py.relative_to(_APPS_DIR))
                for py in sorted(directory.glob("*.py"))
                if py.name != "__init__.py"
            )
            continue  # container is not itself an app; its subdirs are handled below
        if not _has_direct_py(directory):
            continue
        if any(parent in roots for parent in directory.parents):
            continue
        roots.append(directory)
        names.append(str(rel))
    # Whole-container apps the conftest loads as a single repo (root = container);
    # `--all` must rebuild these too or they drift stale (FLAW-309). They are built
    # FIRST: a container's artifact dir nests its sub-apps' dirs inside it, and
    # `_generate` rmtree's the whole container dir, so a sub-app must be (re)built
    # AFTER its parent or the parent build would wipe it.
    whole = [
        w for w in sorted(_WHOLE_CONTAINER_APPS) if (_APPS_DIR / w).is_dir() and w not in names
    ]
    return whole + names


def _assert_portable(out: Path, *, repo_root: Path, artifact_root: Path) -> None:
    """Fail loudly if any normalized artifact embeds a machine-specific path.

    L1 relativizes every path/FQN at the source — semgrep-derived ``caller_fqn``/
    ``callee_fqn``/``fqn``/``file`` and ``provenance.artifact`` included — so a
    freshly built artifact must contain NO absolute generation root. This is the
    portability tripwire that replaced the sentinel-rewriting band-aid: a future
    producer that reintroduces an absolute path/FQN field fails the build here,
    with the offending file and root named, rather than silently shipping a
    machine-bound (non-portable) artifact.
    """
    needles = {
        "repo_root": str(repo_root),
        "artifact_root": str(artifact_root),
        "home": str(Path.home()),
    }
    normalized = out / "normalized"
    offenders: list[str] = []
    for path in sorted(normalized.rglob("*")):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        offenders.extend(
            f"{path.name}: {label} ({needle})"
            for label, needle in needles.items()
            if needle in text
        )
    if offenders:
        msg = (
            f"non-portable artifacts for {out.name}: absolute machine paths leaked "
            f"into normalized facts — the L1 producer must emit repo-relative "
            f"paths/FQNs at the source. Offenders: {offenders}"
        )
        raise SystemExit(msg)


def _generate(name: str) -> tuple[float, int]:
    """Build one app's artifacts; return (seconds, normalized bytes)."""
    app = _app_path(name)
    out = _ARTIFACTS_DIR / name
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    start = time.perf_counter()
    # validate=True: fail-CLOSED on blocking L1 representation drift at mint time,
    # so a regenerated artifact can never silently carry an under-qualified FQN.
    build_index(app, artifact_root=out, validate=True)
    elapsed = time.perf_counter() - start

    # Keep normalized/ only — raw/ (semgrep core output) is not read at load time.
    raw = out / "raw"
    if raw.exists():
        shutil.rmtree(raw)
    for stray in out.iterdir():
        if stray.name != "normalized":
            stray.unlink() if stray.is_file() else shutil.rmtree(stray)

    # build_index resolves both roots internally, and normalizes a single-file
    # repo_root to its PARENT directory (_pipeline.py: `if repo_root.is_file()`),
    # recording paths relative to that parent. Match that effective root so the
    # portability guard checks against the same absolute prefix the build saw.
    effective_repo_root = app.resolve().parent if app.is_file() else app.resolve()
    _assert_portable(out, repo_root=effective_repo_root, artifact_root=out.resolve())

    (out / _STAMP_NAME).write_text(_PIPELINE_VERSION + "\n", encoding="utf-8")

    size = sum(f.stat().st_size for f in (out / "normalized").rglob("*") if f.is_file())
    return elapsed, size


def _generate_named(name: str) -> tuple[str, float, int]:
    """``_generate`` for a Pool worker: pair the result with its app name, and
    convert any worker-side failure (including the ``SystemExit`` the portability
    guard / missing-app check raise) into a picklable ``RuntimeError`` so it
    propagates to the parent and fails the build loudly instead of hanging the Pool.
    """
    try:
        elapsed, size = _generate(name)
    except (Exception, SystemExit) as exc:
        msg = f"fixture build failed for {name}: {exc}"
        raise RuntimeError(msg) from exc
    return name, elapsed, size


def _is_fresh(name: str) -> bool:
    stamp = _ARTIFACTS_DIR / name / _STAMP_NAME
    return stamp.is_file() and stamp.read_text(encoding="utf-8").strip() == _PIPELINE_VERSION


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("apps", nargs="*", help="fixture app names under tests/fixtures/apps/")
    parser.add_argument("--all", action="store_true", help="build every fixture app")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any named app's artifacts are missing or stale",
    )
    parser.add_argument(
        "-j",
        "--jobs",
        type=int,
        default=os.cpu_count() or 1,
        help="parallel build workers (default: CPU count; 1 = serial). Ignored by --check.",
    )
    args = parser.parse_args(argv)

    names = _all_apps() if args.all else args.apps
    if not names:
        parser.error("name at least one app, or pass --all")

    if args.check:
        stale = [n for n in names if not _is_fresh(n)]
        if stale:
            print(f"STALE/MISSING artifacts (pipeline {_PIPELINE_VERSION}): {', '.join(stale)}")
            return 1
        print(f"all {len(names)} artifact set(s) fresh at pipeline {_PIPELINE_VERSION}")
        return 0

    def _report(name: str, elapsed: float, size: int) -> None:
        print(f"  {name:<28} {elapsed:6.1f}s  {size / 1024:8.0f} KiB normalized")

    # An app whose artifact dir nests another selected app's must build BEFORE that
    # child, never concurrently: _generate rmtree's the whole app dir and would wipe
    # the child's freshly built artifacts (the _WHOLE_CONTAINER_APPS case). Build
    # those parents first and serially; every remaining app is path-disjoint.
    parents = [n for n in names if any(o != n and o.startswith(n + "/") for o in names)]
    parallel = [n for n in names if n not in parents]

    total = 0
    for name in parents:
        elapsed, size = _generate(name)
        total += size
        _report(name, elapsed, size)

    jobs = max(1, args.jobs)
    if jobs > 1 and len(parallel) > 1:
        with multiprocessing.Pool(jobs) as pool:
            for name, elapsed, size in pool.imap_unordered(_generate_named, parallel):
                total += size
                _report(name, elapsed, size)
    else:
        for name in parallel:
            elapsed, size = _generate(name)
            total += size
            _report(name, elapsed, size)

    print(f"built {len(names)} app(s); {total / 1024 / 1024:.1f} MiB normalized total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
